apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer
  namespace: matchlabels2
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app2: backend 
