apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalancer
  namespace: matchlabels2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: app-frontend  
